Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.ht8nqI2iu6/Render
COLORTERM=truecolor
COMMAND_MODE=unix2003
GIT_ASKPASS=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
HOME=/Users/bamghoug
LANG=en_US.UTF-8
LOGNAME=bamghoug
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki
PWD=/Users/bamghoug/Desktop/mini2
SECURITYSESSIONID=186a8
SHELL=/bin/bash
SHLVL=3
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.6Ft4gp5tEI/Listeners
TERM=xterm-256color
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.52.1
TMPDIR=/var/folders/zz/zyxvpxvq6csfxvn_n00004_w00012q/T/
USER=bamghoug
VSCODE_GIT_ASKPASS_MAIN=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)
VSCODE_GIT_IPC_HANDLE=/var/folders/zz/zyxvpxvq6csfxvn_n00004_w00012q/T/vscode-git-a46f1a985f.sock
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
_=env
__CF_USER_TEXT_ENCODING=0x457:0:0
a=\b \ n\ \ \ \ \ 
